name: Format

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Install dependencies
       run: npm ci

     - name: Run formatter
       run: npm run fmt:check
