name: Lint

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Install dependencies
       run: npm ci

     - name: Run linter
       run: npm run lint
